name: verzo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.3.0
  graphql_flutter: ^5.1.2
  shared_preferences: ^2.2.2
  typesense: ^0.4.0
  sqflite: ^2.3.0
  google_fonts: ^5.0.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.5
  intl: ^0.19.0
  get: ^4.6.6
  path: ^1.8.3
  calendar_date_picker2: ^0.5.5
  flutter_launcher_icons: ^0.13.1
  form_field_validator: ^1.1.0
  responsive_sizer: ^3.3.1
  webview_flutter: ^3.0.1
  dropdown_button2: ^2.3.9
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^17.2.1+1
  provider: ^6.0.3


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/Icon_launcher2.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
        - assets/images/verzo_logo 1.svg
        - assets/images/Icon_launcher.png
        - assets/images/Icon_launcher2.png
        - assets/images/Frame_43540.svg
        - assets/images/Frame 43540.svg
        - assets/images/Frame 43540-1.svg
        - assets/images/Frame_43540-2.svg
        - assets/images/Frame_43540-3.svg
        - assets/images/Frame_43540-4.svg
        - assets/images/Frame_43540-5.svg
        - assets/images/Frame_43540-6.svg
        - assets/images/Frame_43540-6.svg
        - assets/images/Frame_43540-7.svg
        - assets/images/Frame_43540-8.svg
        - assets/images/Frame_43540-9.svg
        - assets/images/Group_1000007828.svg
        - assets/images/Group_1000007816.svg
        - assets/images/Group_1000007844.svg
        - assets/images/Group_1000007830.svg
        - assets/images/Group_1000007808.svg
        - assets/images/Group 1000007811.svg
        - assets/images/Group 1000007812.svg
        - assets/images/Group 1000007839.svg
        - assets/images/Group 1000007841.svg
        - assets/images/Group 1000007942.svg
        - assets/images/Group 1000007944.svg
        - assets/images/Group 1000007949.svg
        - assets/images/Group 1000007963.svg
        - assets/images/Frame_1000007862.svg
        - assets/images/Frame 1000007915.svg
        - assets/images/trending_up.svg
        - assets/images/Group_search.svg
        - assets/images/Group_2780.svg
        - assets/images/Group 2171.svg
        - assets/images/Group 2984.svg
        - assets/images/Frame 2171.svg
        - assets/images/Group_3161.svg
        - assets/images/home-02.svg
        - assets/images/home-02-2-3.svg
        - assets/images/edit-03.svg
        - assets/images/edit-contained.svg
        - assets/images/settings.svg
        - assets/images/settings2.svg
        - assets/images/coin-hand.svg
        - assets/images/coin-hand2.svg
        - assets/images/box.svg
        - assets/images/box2.svg
        - assets/images/users-profiles-02.svg
        - assets/images/users-profiles-03.svg
        - assets/images/user-profile-02.svg
        - assets/images/logout-03.svg
        - assets/images/home-02-2.svg
        - assets/images/archive.svg
        - assets/images/archive-2.svg
        - assets/images/eye-open.svg
        - assets/images/eye.svg
        - assets/images/unarchive2.svg
        - assets/images/plus-01.svg
        - assets/images/receipt-lines.svg
        - assets/images/receipt-lines-2.svg
        - assets/images/cart.svg
        - assets/images/cart-2.svg
        - assets/images/email.svg
        - assets/images/share.svg
        - assets/images/check-broken.svg
        - assets/images/card-minus.svg
        - assets/images/card-minus-2.svg
        - assets/images/calendar-02.svg
        - assets/images/calendar-03.svg
        - assets/images/info-circle.svg
        - assets/images/save-01.svg
        - assets/images/trash-01.svg
        - assets/images/trash-04.svg
        - assets/images/wallet-03-2.svg
        - assets/images/wallet-03.svg
        - assets/images/notification-02.svg
        - assets/images/notification-02-2.svg
        - assets/images/employee_settings-2.svg
        - assets/images/employee_settings.svg
        - assets/images/save-02.svg
        - assets/images/MasterCard.svg
        - assets/images/card.svg
        - assets/images/Rectangle-331.svg
        - assets/images/verve.svg


  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/satoshiregular.ttf

















  # fonts:
  #   - family: Satoshi
  #     fonts:
  #       - asset: lib/assets/fonts/Satoshi-Regular.ttf
  #         # - asset: fonts/Schyler-Italic.ttf
  #           # style: italic
  #   #   - family: Trajan Pro
  #   #     fonts:
  #   #       - asset: fonts/TrajanPro.ttf
  #   #       - asset: fonts/TrajanPro_Bold.ttf
  #   #         weight: 700
  #   #
  #   # For details regarding fonts from package dependencies,
  #   # see https://flutter.dev/custom-fonts/#from-packages

