// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7M12_46h-OWLqQBLWHxNfj9AyR00xQ3c',
    appId: '1:532715957064:web:9dfaa4a1de778e21d2a17d',
    messagingSenderId: '532715957064',
    projectId: 'verzo-83af7',
    authDomain: 'verzo-83af7.firebaseapp.com',
    storageBucket: 'verzo-83af7.appspot.com',
    measurementId: 'G-47DG37P3EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyv_08NLI_6Ke-X3gCr_IOWYQ-cnM_lZc',
    appId: '1:532715957064:android:6eecc88c6a2eba30d2a17d',
    messagingSenderId: '532715957064',
    projectId: 'verzo-83af7',
    storageBucket: 'verzo-83af7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0RYwOoEDEnAh6pggfUIwE3oXFWU34_-A',
    appId: '1:532715957064:ios:b62b81036413e3c1d2a17d',
    messagingSenderId: '532715957064',
    projectId: 'verzo-83af7',
    storageBucket: 'verzo-83af7.appspot.com',
    iosBundleId: 'verzo.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0RYwOoEDEnAh6pggfUIwE3oXFWU34_-A',
    appId: '1:532715957064:ios:b62b81036413e3c1d2a17d',
    messagingSenderId: '532715957064',
    projectId: 'verzo-83af7',
    storageBucket: 'verzo-83af7.appspot.com',
    iosBundleId: 'verzo.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7M12_46h-OWLqQBLWHxNfj9AyR00xQ3c',
    appId: '1:532715957064:web:744707fab42fdca7d2a17d',
    messagingSenderId: '532715957064',
    projectId: 'verzo-83af7',
    authDomain: 'verzo-83af7.firebaseapp.com',
    storageBucket: 'verzo-83af7.appspot.com',
    measurementId: 'G-ZWKD490EC1',
  );
}
