// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6QwUeBYcHiaBGyy69zs27w3OwmdZewVg',
    appId: '1:714820134583:web:5533171b2ef8ef7fdd4f32',
    messagingSenderId: '714820134583',
    projectId: 'verzo-3a3c9',
    authDomain: 'verzo-3a3c9.firebaseapp.com',
    storageBucket: 'verzo-3a3c9.appspot.com',
    measurementId: 'G-Y1DHFRWWE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdm6DMf5lZazK6FIGsZJIqoD6VPYgHhq8',
    appId: '1:714820134583:android:61ad4039e2b88c0cdd4f32',
    messagingSenderId: '714820134583',
    projectId: 'verzo-3a3c9',
    storageBucket: 'verzo-3a3c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_33Yi-SPY_OjIkaxYCutxDqMeuHn9PGw',
    appId: '1:714820134583:ios:711cb4eed51f0856dd4f32',
    messagingSenderId: '714820134583',
    projectId: 'verzo-3a3c9',
    storageBucket: 'verzo-3a3c9.appspot.com',
    iosBundleId: 'com.example.verzo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_33Yi-SPY_OjIkaxYCutxDqMeuHn9PGw',
    appId: '1:714820134583:ios:711cb4eed51f0856dd4f32',
    messagingSenderId: '714820134583',
    projectId: 'verzo-3a3c9',
    storageBucket: 'verzo-3a3c9.appspot.com',
    iosBundleId: 'com.example.verzo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6QwUeBYcHiaBGyy69zs27w3OwmdZewVg',
    appId: '1:714820134583:web:8e91918b36fa3e50dd4f32',
    messagingSenderId: '714820134583',
    projectId: 'verzo-3a3c9',
    authDomain: 'verzo-3a3c9.firebaseapp.com',
    storageBucket: 'verzo-3a3c9.appspot.com',
    measurementId: 'G-JP1XDLH2GZ',
  );
}
